# Generated by Django 3.1.1 on 2020-09-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addr',
            fields=[
                ('addr_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('addr_name', models.CharField(max_length=45)),
                ('addr_tel', models.CharField(max_length=11)),
                ('addr_addr', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='AdminStrator',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_pwd', models.CharField(max_length=45)),
                ('admin_name', models.CharField(max_length=45, unique=True)),
                ('admin_tel', models.IntegerField(unique=True)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=80)),
                ('book_author', models.CharField(max_length=20)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('book_type', models.CharField(max_length=25)),
                ('book_amount', models.IntegerField(default=1)),
                ('book_time', models.CharField(max_length=20)),
                ('book_sales', models.IntegerField(default=0)),
                ('book_decription', models.CharField(max_length=300, null=True)),
                ('book_img', models.ImageField(upload_to='book_image')),
                ('seller_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('car_amount', models.IntegerField(default=1)),
                ('car_total_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('clt_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('seller_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('orderby_id', models.IntegerField()),
                ('comment_info', models.CharField(max_length=600)),
                ('book_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_addr_id', models.IntegerField()),
                ('order_time', models.CharField(max_length=40)),
                ('buyer_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderBy',
            fields=[
                ('orderby_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('order_amount', models.IntegerField()),
                ('orderby_price', models.CharField(default='0', max_length=20)),
                ('orderby_pay_status', models.IntegerField(default=1)),
                ('seller_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('user_sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('user_pwd', models.CharField(max_length=2000)),
                ('user_tel', models.CharField(max_length=11, unique=True)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_money', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user_score', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('user_img', models.ImageField(null=True, upload_to='user_image')),
                ('user_decription', models.CharField(default='', max_length=80, null=True)),
            ],
        ),
    ]
